# Generated by Django 3.0.8 on 2020-09-12 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IRIB_Auth', '0002_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
    ]
