# Generated by Django 3.0.8 on 2020-09-15 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IRIB_Auth', '0004_auto_20200912_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_id',
        ),
    ]
