# Generated by Django 3.0.8 on 2020-12-20 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IRIB_Auth', '0005_remove_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='access_level',
            field=models.CharField(choices=[('user', 'User'), ('secretary', 'Secretary'), ('scoped_secretary', 'Scoped Secretary')], default='user', max_length=20, verbose_name='Access Level'),
        ),
    ]
