# Generated by Django 3.0.8 on 2021-07-04 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IRIB_Auth', '0006_auto_20201220_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='personnel_number',
            field=models.CharField(blank=True, max_length=15, verbose_name='Personnel Number'),
        ),
    ]
