# Generated by Django 3.0.8 on 2020-07-22 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EIRIB_FollowUp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enactment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField(default=1, unique=True, verbose_name='Row')),
                ('code', models.IntegerField(default=1, verbose_name='Code')),
                ('description', models.TextField(blank=True, max_length=4000, null=True, verbose_name='Description')),
                ('subject', models.CharField(blank=True, max_length=4000, null=True, verbose_name='Subject')),
                ('first_actor', models.CharField(blank=True, max_length=200, null=True, verbose_name='First Actor')),
                ('second_actor', models.CharField(blank=True, max_length=200, null=True, verbose_name='Second Actor')),
                ('date', models.CharField(blank=True, max_length=10, null=True, verbose_name='Assignment Date')),
                ('follow_grade', models.CharField(blank=True, max_length=10, null=True, verbose_name='Follow Grade')),
                ('result', models.TextField(blank=True, max_length=4000, null=True, verbose_name='Result')),
                ('session', models.CharField(blank=True, max_length=200, null=True, verbose_name='Session')),
                ('assigner', models.CharField(blank=True, max_length=200, null=True, verbose_name='Task Assigner')),
                ('first_supervisor', models.CharField(blank=True, max_length=200, null=True, verbose_name='First Supervisor')),
                ('second_supervisor', models.CharField(blank=True, max_length=200, null=True, verbose_name='Second Supervisor')),
                ('review_date', models.CharField(blank=True, max_length=10, null=True, verbose_name='Review Date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Enactment',
                'verbose_name_plural': 'Enactments',
                'ordering': ['date', 'description'],
            },
        ),
    ]
