# Generated by Django 3.0.8 on 2020-07-23 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EIRIB_FollowUp', '0004_remove_enactment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enactment',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='EIRIB_FollowUp.Session', verbose_name='Session'),
        ),
    ]
