# Generated by Django 3.0.8 on 2020-07-23 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EIRIB_FollowUp', '0005_auto_20200723_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enactment',
            name='date',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Assignment Date'),
        ),
        migrations.AlterField(
            model_name='enactment',
            name='follow_grade',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Follow Grade'),
        ),
        migrations.AlterField(
            model_name='enactment',
            name='review_date',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Review Date'),
        ),
        migrations.AlterField(
            model_name='user',
            name='_title',
            field=models.CharField(choices=[('Mr', 'Mr'), ('Mrs', 'Mrs')], default='Mr', max_length=100, verbose_name='Title'),
        ),
    ]
