# Generated by Django 3.0.8 on 2020-07-23 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EIRIB_FollowUp', '0006_auto_20200723_1215'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assigner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2000, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Task Assigner',
                'verbose_name_plural': 'Task Assigners',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='session',
            name='name',
            field=models.CharField(max_length=2000, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='enactment',
            name='assigner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='EIRIB_FollowUp.Assigner', verbose_name='Task Assigner'),
        ),
    ]
