# Generated by Django 3.0.8 on 2020-07-23 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EIRIB_FollowUp', '0008_auto_20200723_1805'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(blank=True, max_length=2000, null=True, verbose_name='First Name')),
                ('lname', models.CharField(max_length=2000, verbose_name='Last Name')),
            ],
            options={
                'verbose_name': 'Actor',
                'verbose_name_plural': 'Actors',
                'ordering': ['lname', 'fname'],
                'unique_together': {('lname', 'fname')},
            },
        ),
        migrations.AlterField(
            model_name='enactment',
            name='first_actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_actor', to='EIRIB_FollowUp.Actor', verbose_name='First Actor'),
        ),
        migrations.AlterField(
            model_name='enactment',
            name='second_actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_actor', to='EIRIB_FollowUp.Actor', verbose_name='Second Actor'),
        ),
    ]
