# Generated by Django 3.0.8 on 2020-07-24 10:48

import EIRIB_FollowUp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EIRIB_FollowUp', '0010_auto_20200723_2003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Description')),
                ('file', models.FileField(upload_to=EIRIB_FollowUp.models.Attachment.directory_path, verbose_name='File')),
                ('enactment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EIRIB_FollowUp.Enactment', verbose_name='Enactment')),
            ],
            options={
                'verbose_name': 'Attachment',
                'verbose_name_plural': 'Attachments',
                'ordering': ['description'],
            },
        ),
    ]
