# Generated by Django 3.0.8 on 2020-07-24 20:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EIRIB_FollowUp', '0011_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='query',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=[], verbose_name='Code'), default=[], size=100000),
            preserve_default=False,
        ),
    ]
