# Generated by Django 3.0.8 on 2020-08-02 14:40

import EIRIB_FollowUp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EIRIB_FollowUp', '0012_user_query'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actor',
            options={'ordering': ['lname', 'fname'], 'verbose_name': 'Supervisor', 'verbose_name_plural': 'Supervisors'},
        ),
        migrations.AlterModelOptions(
            name='enactment',
            options={'ordering': ['review_date', 'row'], 'verbose_name': 'Enactment', 'verbose_name_plural': 'Enactments'},
        ),
        migrations.AlterModelOptions(
            name='supervisor',
            options={'ordering': ['name'], 'verbose_name': 'Supervisor Unit', 'verbose_name_plural': 'Supervisor Units'},
        ),
        migrations.AlterField(
            model_name='enactment',
            name='date',
            field=models.DateField(default=EIRIB_FollowUp.models.set_now, verbose_name='Assignment Date'),
        ),
        migrations.AlterField(
            model_name='enactment',
            name='review_date',
            field=models.DateField(default=EIRIB_FollowUp.models.set_now, verbose_name='Review Date'),
        ),
    ]
