# Generated by Django 3.0.8 on 2020-08-03 12:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EIRIB_FollowUp', '0013_auto_20200802_1440'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enactment',
            options={'ordering': ['-review_date', 'row'], 'verbose_name': 'Enactment', 'verbose_name_plural': 'Enactments'},
        ),
        migrations.AlterField(
            model_name='user',
            name='query',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0, verbose_name='Code'), size=100000),
        ),
        migrations.AlterField(
            model_name='user',
            name='query_name',
            field=models.CharField(max_length=200, verbose_name='Query Name'),
        ),
    ]
