# Generated by Django 3.0.8 on 2020-08-03 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EIRIB_FollowUp', '0014_auto_20200803_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='User ID'),
        ),
    ]
