# Generated by Django 3.0.8 on 2020-08-09 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EIRIB_FollowUp', '0015_user_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='supervisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='EIRIB_FollowUp.Supervisor', verbose_name='Supervisor Unit'),
        ),
    ]
