# Generated by Django 3.0.8 on 2020-08-09 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EIRIB_FollowUp', '0016_actor_supervisor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enactment',
            name='first_supervisor',
        ),
        migrations.RemoveField(
            model_name='enactment',
            name='second_supervisor',
        ),
    ]
