# Generated by Django 3.0.8 on 2020-08-26 15:15

import EIRIB_FollowUp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EIRIB_FollowUp', '0017_auto_20200809_1146'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enactment',
            options={'ordering': ['-review_date', '-date', 'session', 'subject', 'row'], 'verbose_name': 'Enactment', 'verbose_name_plural': 'Enactments'},
        ),
        migrations.AlterField(
            model_name='enactment',
            name='date',
            field=models.DateTimeField(default=EIRIB_FollowUp.models.set_now, verbose_name='Assignment Date'),
        ),
        migrations.AlterField(
            model_name='enactment',
            name='review_date',
            field=models.DateTimeField(default=EIRIB_FollowUp.models.set_now, verbose_name='Review Date'),
        ),
    ]
