# Generated by Django 3.0.8 on 2020-09-10 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EIRIB_FollowUp', '0018_auto_20200826_1515'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enactment',
            options={'ordering': ['-_review_date', '-_date', 'session', 'subject', 'row'], 'verbose_name': 'Enactment', 'verbose_name_plural': 'Enactments'},
        ),
        migrations.RenameField(
            model_name='enactment',
            old_name='date',
            new_name='_date',
        ),
        migrations.RenameField(
            model_name='enactment',
            old_name='review_date',
            new_name='_review_date',
        ),
    ]
