# Generated by Django 3.0.8 on 2020-09-15 13:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EIRIB_FollowUp', '0020_auto_20200915_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='query',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0, verbose_name='Code'), blank=True, null=True, size=100000),
        ),
    ]
