# Generated by Django 3.0.8 on 2020-09-15 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EIRIB_FollowUp', '0021_auto_20200915_1312'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
