# Generated by Django 3.0.8 on 2020-09-15 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EIRIB_FollowUp', '0023_user__user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='_user_id',
        ),
    ]
