# Generated by Django 3.0.8 on 2020-11-22 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EIRIB_FollowUp', '0024_remove_user__user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enactment',
            name='result',
            field=models.TextField(default='', max_length=4000, verbose_name='Result'),
        ),
    ]
