# Generated by Django 3.0.8 on 2020-09-01 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2000, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Knowledge Activity',
                'verbose_name_plural': 'Knowledge Activities',
                'ordering': ['name'],
            },
        ),
    ]
