# Generated by Django 3.0.8 on 2020-09-01 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Knowledge_Management', '0002_auto_20200901_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2000, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Knowledge Category',
                'verbose_name_plural': 'Knowledge Categories',
                'ordering': ['name'],
            },
        ),
    ]
