# Generated by Django 3.0.8 on 2020-09-04 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Knowledge_Management', '0007_activityassessment_attachment_cardtablebase'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalCardtable',
            fields=[
            ],
            options={
                'verbose_name': 'Personal Cardtable',
                'verbose_name_plural': 'Personal Cardtables',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Knowledge_Management.cardtablebase',),
        ),
    ]
