# Generated by Django 3.0.8 on 2020-09-04 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Knowledge_Management', '0008_personalcardtable'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentCardtable',
            fields=[
            ],
            options={
                'verbose_name': 'Assessment Cardtable',
                'verbose_name_plural': 'Assessment Cardtables',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Knowledge_Management.cardtablebase',),
        ),
    ]
