# Generated by Django 3.0.8 on 2020-09-04 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Knowledge_Management', '0009_assessmentcardtable'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialCardtable',
            fields=[
            ],
            options={
                'verbose_name': 'Financial Cardtable',
                'verbose_name_plural': 'Financial Cardtables',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Knowledge_Management.cardtablebase',),
        ),
    ]
