# Generated by Django 3.0.8 on 2020-09-04 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Knowledge_Management', '0010_financialcardtable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityassessment',
            name='score',
        ),
        migrations.AddField(
            model_name='activityassessment',
            name='scores',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Scores'),
        ),
    ]
