# Generated by Django 3.0.8 on 2020-09-07 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Knowledge_Management', '0013_auto_20200905_0826'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardtablebase',
            old_name='date',
            new_name='_date',
        ),
    ]
