# Generated by Django 3.0.8 on 2020-09-07 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Knowledge_Management', '0015_auto_20200907_1215'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivitySubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardtable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Knowledge_Management.CardtableBase', verbose_name='Activity')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Knowledge_Management.SubCategory', verbose_name='Knowledge Sub-Category')),
            ],
            options={
                'verbose_name': 'Activity SubCategory',
                'verbose_name_plural': 'Activity SubCategories',
                'ordering': ['cardtable', 'subcategory'],
                'unique_together': {('cardtable', 'subcategory')},
            },
        ),
    ]
