# Generated by Django 3.0.8 on 2020-09-07 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Knowledge_Management', '0016_activitysubcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='committeemember',
            name='secretary',
            field=models.BooleanField(default=False, verbose_name='Secretary'),
        ),
    ]
