# Generated by Django 3.0.8 on 2020-09-15 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Knowledge_Management', '0017_committeemember_secretary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cardtablebase',
            options={'ordering': ['id'], 'verbose_name': 'Cardtable Base', 'verbose_name_plural': 'Cardtable Bases'},
        ),
    ]
