# Generated by Django 3.0.8 on 2020-09-18 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Knowledge_Management', '0018_auto_20200915_0938'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='committeemember',
            options={'ordering': ['user'], 'verbose_name': 'Committee Member', 'verbose_name_plural': 'Committee Members'},
        ),
        migrations.AddField(
            model_name='cardtablebase',
            name='secretary_description',
            field=models.TextField(blank=True, max_length=4000, null=True, verbose_name='Secretary Description'),
        ),
    ]
