# Generated by Django 3.0.8 on 2020-09-21 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Knowledge_Management', '0019_auto_20200918_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardtablebase',
            name='_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('NEW', 'New'), ('ACCEPTED', 'Accepted'), ('EDIT_NEEDED', 'Edit needed'), ('REJECTED', 'Rejected'), ('CONDITIONAL', 'Conditional'), ('APPROVED', 'Approved')], default='DRAFT', max_length=30, verbose_name='Status'),
        ),
    ]
