# Generated by Django 3.0.8 on 2020-09-21 13:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Knowledge_Management', '0020_auto_20200921_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityassessment',
            name='scores',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0, verbose_name='Score'), blank=True, null=True, size=1000, verbose_name='Scores'),
        ),
    ]
