# Generated by Django 3.0.8 on 2020-09-21 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Knowledge_Management', '0021_auto_20200921_1329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activityassessment',
            old_name='scores',
            new_name='_scores',
        ),
    ]
