# Generated by Django 3.0.8 on 2020-09-22 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Knowledge_Management', '0022_auto_20200921_1342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activityassessment',
            old_name='date',
            new_name='_date',
        ),
    ]
