# Generated by Django 3.0.8 on 2020-09-27 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaySlip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('1', 'Farvardin'), ('2', 'Ordibehesht'), ('3', 'Khordad'), ('4', 'Tir'), ('5', 'Mordad'), ('6', 'Shahrivar'), ('7', 'Mehr'), ('8', 'Aban'), ('9', 'Azar'), ('10', 'Day'), ('11', 'Bahman'), ('12', 'Esfand')], default='1', max_length=30, verbose_name='Month')),
                ('year', models.IntegerField(default=99, verbose_name='Year')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Full Name')),
                ('personnel_id', models.CharField(blank=True, max_length=20, verbose_name='Personnel ID')),
                ('account_no', models.CharField(blank=True, max_length=50, verbose_name='Account Number')),
                ('insurance_no', models.CharField(blank=True, max_length=50, verbose_name='Insurance Number')),
                ('department', models.CharField(blank=True, max_length=200, verbose_name='Department')),
                ('working_place', models.CharField(blank=True, max_length=200, verbose_name='Working Place')),
                ('job_title', models.CharField(blank=True, max_length=200, verbose_name='Job Title')),
                ('basic_salary', models.IntegerField(default=0, verbose_name='Basic Salary')),
                ('supplementary_allowance', models.IntegerField(default=0, verbose_name='Supplementary Allowance')),
                ('operation', models.IntegerField(default=0, verbose_name='Operation')),
                ('overtime_working', models.IntegerField(default=0, verbose_name='Overtime Working')),
                ('children_allowance', models.IntegerField(default=0, verbose_name='Children Allowance')),
                ('grocery_salary', models.IntegerField(default=0, verbose_name='Grocery Allowance')),
                ('housing_salary', models.IntegerField(default=0, verbose_name='Housing Allowance')),
                ('spouse_salary', models.IntegerField(default=0, verbose_name='Spouse Allowance')),
                ('mobile_salary', models.IntegerField(default=0, verbose_name='Mobile  Allowance')),
                ('food_cost', models.IntegerField(default=0, verbose_name='Food Cost')),
                ('insurance', models.IntegerField(default=0, verbose_name='Insurance')),
                ('tax', models.IntegerField(default=0, verbose_name='Tax')),
                ('loan_installments', models.IntegerField(default=0, verbose_name='Loan Installments')),
                ('supplementary_insurance', models.IntegerField(default=0, verbose_name='Supplementary Insurance')),
                ('leave_balance', models.IntegerField(default=0, verbose_name='Leave Balance')),
                ('atieh_balance', models.IntegerField(default=0, verbose_name='Atieh Fund Balance')),
                ('refah_balance', models.IntegerField(default=0, verbose_name='Refah Fund Balance')),
            ],
            options={
                'verbose_name': 'Pay Slip',
                'verbose_name_plural': 'Pay Slips',
            },
        ),
    ]
