# Generated by Django 3.0.8 on 2020-09-27 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IRIB_HR', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='post_allowance',
            field=models.IntegerField(default=0, verbose_name='Post Allowance'),
        ),
        migrations.AddField(
            model_name='payslip',
            name='special_allowance',
            field=models.IntegerField(default=0, verbose_name='Special Allowance'),
        ),
    ]
