# Generated by Django 3.0.8 on 2020-09-28 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IRIB_HR', '0002_auto_20200927_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='national_id',
            field=models.CharField(blank=True, max_length=20, verbose_name='National ID'),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='month',
            field=models.CharField(choices=[('01', 'Farvardin'), ('02', 'Ordibehesht'), ('03', 'Khordad'), ('04', 'Tir'), ('05', 'Mordad'), ('06', 'Shahrivar'), ('07', 'Mehr'), ('08', 'Aban'), ('09', 'Azar'), ('10', 'Day'), ('11', 'Bahman'), ('12', 'Esfand')], default='01', max_length=30, verbose_name='Month'),
        ),
    ]
