# Generated by Django 3.0.8 on 2020-09-28 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IRIB_HR', '0003_auto_20200928_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payslip',
            name='name',
        ),
        migrations.AddField(
            model_name='payslip',
            name='first_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='payslip',
            name='last_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='last name'),
        ),
    ]
