# Generated by Django 3.0.8 on 2021-06-08 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IRIB_HR', '0008_auto_20210608_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='_date',
            field=models.DateField(verbose_name='Pay Date'),
        ),
    ]
