# Generated by Django 3.0.8 on 2021-06-13 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IRIB_HR', '0009_auto_20210608_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonus',
            name='description',
            field=models.TextField(blank=True, max_length=4000, null=True, verbose_name='Description'),
        ),
        migrations.CreateModel(
            name='BonusSubType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='IRIB_HR.BonusType', verbose_name='Bonus Type')),
            ],
            options={
                'verbose_name': 'Bonus Sub Type',
                'verbose_name_plural': 'Bonus Sub Types',
                'ordering': ['title'],
                'unique_together': {('title', 'type')},
            },
        ),
        migrations.AlterField(
            model_name='bonus',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='IRIB_HR.BonusSubType', verbose_name='Type'),
        ),
    ]
