# Generated by Django 3.0.8 on 2021-06-14 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('IRIB_HR', '0010_auto_20210613_1027'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bonussubtype',
            options={'ordering': ['type', 'title'], 'verbose_name': 'Bonus Sub Type', 'verbose_name_plural': 'Bonus Sub Types'},
        ),
        migrations.AddField(
            model_name='bonustype',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.Group', verbose_name='Allowed Group'),
        ),
    ]
