# Generated by Django 3.0.8 on 2021-07-07 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IRIB_HR', '0012_attachment_personalinquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinquiry',
            name='final_result',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Final Result'),
        ),
        migrations.AddField(
            model_name='personalinquiry',
            name='operator_result',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Operator Result'),
        ),
        migrations.AddField(
            model_name='personalinquiry',
            name='security_result',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Security Result'),
        ),
        migrations.AlterField(
            model_name='personalinquiry',
            name='_birthdate',
            field=models.DateField(blank=True, null=True, verbose_name='birthdate'),
        ),
        migrations.AlterField(
            model_name='personalinquiry',
            name='address',
            field=models.TextField(blank=True, max_length=4000, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='personalinquiry',
            name='alias',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='alias'),
        ),
        migrations.AlterField(
            model_name='personalinquiry',
            name='background',
            field=models.TextField(blank=True, max_length=4000, null=True, verbose_name='job background'),
        ),
        migrations.AlterField(
            model_name='personalinquiry',
            name='birth_place',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='birth place'),
        ),
        migrations.AlterField(
            model_name='personalinquiry',
            name='description',
            field=models.TextField(blank=True, max_length=4000, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='personalinquiry',
            name='educational_stage',
            field=models.CharField(blank=True, choices=[('preschool', 'Preschool'), ('primary', 'Primary'), ('lower', 'Lower secondary'), ('upper', 'Upper secondary'), ('bachelor', 'Bachelors or equivalent'), ('master', 'Masters or equivalent'), ('doctoral', 'Doctoral or equivalent')], default='upper', max_length=50, null=True, verbose_name='educational stage'),
        ),
        migrations.AlterField(
            model_name='personalinquiry',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email address'),
        ),
        migrations.AlterField(
            model_name='personalinquiry',
            name='father_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='father name'),
        ),
        migrations.AlterField(
            model_name='personalinquiry',
            name='id_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='ID number'),
        ),
        migrations.AlterField(
            model_name='personalinquiry',
            name='issue_place',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='issue place'),
        ),
        migrations.AlterField(
            model_name='personalinquiry',
            name='national_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='National ID'),
        ),
        migrations.AlterField(
            model_name='personalinquiry',
            name='personal_no',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='personal number'),
        ),
        migrations.AlterField(
            model_name='personalinquiry',
            name='religion',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='religion'),
        ),
    ]
