# Generated by Django 3.0.8 on 2021-07-10 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IRIB_HR', '0013_auto_20210707_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinquiry',
            name='final_result',
        ),
        migrations.RemoveField(
            model_name='personalinquiry',
            name='operator_result',
        ),
        migrations.RemoveField(
            model_name='personalinquiry',
            name='security_result',
        ),
        migrations.AddField(
            model_name='personalinquiry',
            name='final_note',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Final Note'),
        ),
        migrations.AddField(
            model_name='personalinquiry',
            name='final_vote',
            field=models.TextField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('conditional', 'Conditionally approved'), ('pending', 'Pending')], default='pending', max_length=20, verbose_name='Final Vote'),
        ),
        migrations.AddField(
            model_name='personalinquiry',
            name='operator_note',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Operator Note'),
        ),
        migrations.AddField(
            model_name='personalinquiry',
            name='operator_vote',
            field=models.TextField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('conditional', 'Conditionally approved'), ('pending', 'Pending')], default='pending', max_length=20, verbose_name='Operator Vote'),
        ),
        migrations.AddField(
            model_name='personalinquiry',
            name='security_note',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Security Note'),
        ),
        migrations.AddField(
            model_name='personalinquiry',
            name='security_vote',
            field=models.TextField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('conditional', 'Conditionally approved'), ('pending', 'Pending')], default='pending', max_length=20, verbose_name='Security Vote'),
        ),
    ]
