# Generated by Django 3.0.8 on 2021-07-10 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('IRIB_HR', '0014_auto_20210710_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinquiry',
            name='registrant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Registrant'),
        ),
        migrations.AlterField(
            model_name='personalinquiry',
            name='final_vote',
            field=models.TextField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('conditional', 'Conditional Approve'), ('pending', 'Pending')], default='pending', max_length=20, verbose_name='Final Vote'),
        ),
        migrations.AlterField(
            model_name='personalinquiry',
            name='operator_vote',
            field=models.TextField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('conditional', 'Conditional Approve'), ('pending', 'Pending')], default='pending', max_length=20, verbose_name='Operator Vote'),
        ),
        migrations.AlterField(
            model_name='personalinquiry',
            name='security_vote',
            field=models.TextField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('conditional', 'Conditional Approve'), ('pending', 'Pending')], default='pending', max_length=20, verbose_name='Security Vote'),
        ),
    ]
