# Generated by Django 3.0.8 on 2020-08-25 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IRIB_FollowUp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Response Date')),
                ('result', models.TextField(blank=True, max_length=4000, null=True, verbose_name='Result')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Actor')),
                ('enactment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IRIB_FollowUp.Enactment', verbose_name='Enactment')),
            ],
            options={
                'verbose_name': 'Follow Up',
                'verbose_name_plural': 'Follow Ups',
                'ordering': ['actor__last_name', 'actor__first_name'],
                'unique_together': {('actor', 'enactment')},
            },
        ),
    ]
