# Generated by Django 3.0.8 on 2020-08-25 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IRIB_FollowUp', '0002_followup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enactment',
            name='first_actor',
        ),
        migrations.RemoveField(
            model_name='enactment',
            name='result',
        ),
        migrations.RemoveField(
            model_name='enactment',
            name='second_actor',
        ),
    ]
