# Generated by Django 3.0.8 on 2020-08-26 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IRIB_FollowUp', '0004_auto_20200825_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enactment',
            name='code',
        ),
    ]
