# Generated by Django 3.0.8 on 2020-08-29 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IRIB_FollowUp', '0005_remove_enactment_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='enactment',
            options={'ordering': ['-review_date', '-date', 'session', 'subject', 'id'], 'verbose_name': 'Enactment', 'verbose_name_plural': 'Enactments'},
        ),
    ]
