# Generated by Django 3.0.8 on 2020-08-29 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IRIB_FollowUp', '0006_auto_20200829_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IRIB_FollowUp.Group', verbose_name='Group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Group User',
                'verbose_name_plural': 'Group Users',
                'ordering': ['group', 'user'],
                'unique_together': {('group', 'user')},
            },
        ),
    ]
