# Generated by Django 3.0.8 on 2020-08-30 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IRIB_FollowUp', '0007_groupuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupFollowUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enactment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IRIB_FollowUp.Enactment', verbose_name='Enactment')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IRIB_FollowUp.Group', verbose_name='Group')),
            ],
            options={
                'verbose_name': 'Group FollowUp',
                'verbose_name_plural': 'Group FollowUps',
            },
        ),
    ]
