# Generated by Django 3.0.8 on 2020-09-05 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IRIB_FollowUp', '0009_enactment__type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2000, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Session Base',
                'verbose_name_plural': 'Session Bases',
                'ordering': ['name'],
            },
        ),
    ]
