# Generated by Django 3.0.8 on 2020-09-05 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IRIB_FollowUp', '0010_sessionbase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendant',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='IRIB_FollowUp.SessionBase', verbose_name='Session'),
        ),
    ]
