# Generated by Django 3.0.8 on 2020-09-05 18:27

import IRIB_FollowUp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IRIB_FollowUp', '0011_auto_20200905_1755'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['name', 'date'], 'verbose_name': 'Session', 'verbose_name_plural': 'Sessions'},
        ),
        migrations.AddField(
            model_name='session',
            name='date',
            field=models.DateTimeField(default=IRIB_FollowUp.models.set_now, verbose_name='Attended Date'),
        ),
    ]
