# Generated by Django 3.0.8 on 2020-09-05 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IRIB_FollowUp', '0012_auto_20200905_1827'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['name', '_date'], 'verbose_name': 'Session', 'verbose_name_plural': 'Sessions'},
        ),
        migrations.RenameField(
            model_name='session',
            old_name='date',
            new_name='_date',
        ),
    ]
