# Generated by Django 3.0.8 on 2020-09-06 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IRIB_FollowUp', '0013_auto_20200905_1842'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['session__name', '_date'], 'verbose_name': 'Session', 'verbose_name_plural': 'Sessions'},
        ),
        migrations.RemoveField(
            model_name='session',
            name='name',
        ),
        migrations.AddField(
            model_name='session',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='IRIB_FollowUp.SessionBase', verbose_name='Session'),
        ),
    ]
