# Generated by Django 3.0.8 on 2020-09-06 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IRIB_FollowUp', '0014_auto_20200906_0917'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='IRIB_FollowUp.SessionBase', verbose_name='Session Base')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Members',
                'ordering': ['session__name', 'user__last_name', 'user__first_name'],
                'unique_together': {('session', 'user')},
            },
        ),
        migrations.AlterField(
            model_name='enactment',
            name='_type',
            field=models.CharField(choices=[('AGENDA', 'Agenda'), ('ENACTMENT', 'Enactment'), ('FOR_INFORMATION', 'For Information'), ('REGULATIONS', 'Regulations')], default='FOR_INFORMATION', max_length=30, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='session',
            name='session',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='IRIB_FollowUp.SessionBase', verbose_name='Session Base'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Attendant',
        ),
    ]
