# Generated by Django 3.0.8 on 2020-09-06 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IRIB_FollowUp', '0015_auto_20200906_1006'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='IRIB_FollowUp.Session', verbose_name='Session')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Attendant',
                'verbose_name_plural': 'Attendants',
                'ordering': ['session__session__name', 'user__last_name', 'user__first_name'],
                'unique_together': {('session', 'user')},
            },
        ),
    ]
