# Generated by Django 3.0.8 on 2020-09-06 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IRIB_FollowUp', '0016_attendant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['session__name', '_date'], 'verbose_name': 'Minute', 'verbose_name_plural': 'Minutes'},
        ),
        migrations.AlterModelOptions(
            name='sessionbase',
            options={'ordering': ['name'], 'verbose_name': 'Session', 'verbose_name_plural': 'Sessions'},
        ),
        migrations.AlterField(
            model_name='attendant',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='IRIB_FollowUp.Session', verbose_name='Minute'),
        ),
        migrations.AlterField(
            model_name='enactment',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='IRIB_FollowUp.Session', verbose_name='Minute'),
        ),
        migrations.AlterField(
            model_name='member',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='IRIB_FollowUp.SessionBase', verbose_name='Session'),
        ),
        migrations.AlterField(
            model_name='session',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IRIB_FollowUp.SessionBase', verbose_name='Session'),
        ),
    ]
