# Generated by Django 3.0.8 on 2020-09-06 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IRIB_FollowUp', '0017_auto_20200906_1315'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enactment',
            options={'ordering': ['-_review_date', 'session', 'subject', 'id'], 'verbose_name': 'Enactment', 'verbose_name_plural': 'Enactments'},
        ),
        migrations.AlterModelOptions(
            name='sessionbase',
            options={'ordering': ['name'], 'verbose_name': 'Meeeting', 'verbose_name_plural': 'Meeetings'},
        ),
        migrations.RenameField(
            model_name='enactment',
            old_name='review_date',
            new_name='_review_date',
        ),
        migrations.RenameField(
            model_name='followup',
            old_name='date',
            new_name='_date',
        ),
        migrations.RemoveField(
            model_name='enactment',
            name='date',
        ),
        migrations.AlterField(
            model_name='session',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IRIB_FollowUp.SessionBase', verbose_name='Meeeting'),
        ),
    ]
