# Generated by Django 3.0.8 on 2020-09-08 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IRIB_FollowUp', '0018_auto_20200906_1349'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelTable(
            name='supervisor',
            table='IRIB_Auth_supervisor',
        ),
        migrations.AlterModelTable(
            name='user',
            table='IRIB_Auth_user',
        ),
    ]
