# Generated by Django 3.0.8 on 2020-09-08 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IRIB_Auth', '0001_initial'),
        ('IRIB_FollowUp', '0019_auto_20200908_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='supervisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_set', to='IRIB_Auth.Supervisor', verbose_name='Supervisor Unit'),
        ),
        migrations.DeleteModel(
            name='Supervisor',
        ),
    ]
