# Generated by Django 3.0.8 on 2020-09-12 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IRIB_FollowUp', '0020_auto_20200908_1357'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
