# Generated by Django 3.0.8 on 2020-11-22 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IRIB_FollowUp', '0021_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='result',
            field=models.TextField(default='', max_length=4000, verbose_name='Result'),
        ),
    ]
