# Generated by Django 3.0.8 on 2020-12-20 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IRIB_FollowUp', '0022_auto_20201122_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='result',
            field=models.TextField(blank=True, default=' ', max_length=4000, verbose_name='Result'),
        ),
    ]
